spring.application.name=tienda

# ==============================
# SERVER
# ==============================

server.port=${PORT:8082}

# ==============================
# DATABASE
# ==============================

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:techshop}?sslmode=${DB_SSLMODE:preferred}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ==============================
# SPRING
# ==============================

logging.pattern.dateformat=hh:mm
spring.main.banner-mode=off
spring.thymeleaf.cache=false

# ==============================
# FIREBASE
# ==============================

firebase.bucket.name=techshop-e33f2.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-e33f2-firebase-adminsdk-fbsvc-2d0c3fa0c8.json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sebaslopez2009@gmail.com
spring.mail.password=zsssqcozteznfupm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

servidor.http=localhost